info:
  component: Cloud Native Config Server

server:
  port: 8888

management:
  context-path: /admin

endpoints:
  info:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false

eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config